[package]
name = "vibrix-kernel"
version = "0.0.1"
edition = "2024"
publish = false
license.workspace = true
repository.workspace = true

[features]
default = []
qemu-debugcon = []
panic-probe = []
breakpoint-probe = []
page-fault-probe = []
vm-write-probe = []
vm-unmap-probe = []
pci-irq-probe = ["qemu-debugcon"]

[dependencies]
