[package]
name = "vibrix-init"
version = "0.0.1"
edition = "2024"
publish = false
license.workspace = true
repository.workspace = true

[[bin]]
name = "vibrix-init"
path = "src/main.rs"
test = false
bench = false

[features]
default = []
advisory-lock-probe = []

[dependencies]
vibrix-syscall = { path = "../syscall", version = "=0.0.1" }
